### ISSUE TITLE
Compleanno

### ISSUE THREAD

**Issue by JustMe011** [WEEE-Open/weeelab-telegram-bot#16]
Abbiamo le date di nascita di tutti, facciamo che il bot ogni tanto dice alla gente "buon compleanno"? asd
Cosi' la gente si ricorda (a caso) di essere nel team

**Comment by neskov7** [comment]
Possibile anche collegare il Nick di telegram e effettuare il tag

Il mar 24 ott 2017, 13:19 JustMe011 <notifications@github.com> ha scritto:

**Comment by davecanni** [comment]
@JustMe011 Andrebbe aggiunto nel json se si vuole fare
