### ISSUE TITLE
Sending disturbing messages to the deserters asd

### ISSUE THREAD

**Issue by Hyd3L** [WEEE-Open/weeelab-telegram-bot#17]
Implement a function that checks if somebody is deserting
(made less than 6 hours of service in that month)
and sends a message that tells him sth like
`Clear pacts and long term friendship! 
You must go to the lab for 6 hours a month,
or you'll be punched till death by @JustMe11`

**Comment by lvps** [comment]
Così li convinci proprio tutti tanto ad andare in lab, guarda... asd
