### ISSUE TITLE
Add /logout command

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/weeelab-telegram-bot#45]
Since a lot of people have forgotten to logout from the lab lately, it would be useful to add a /logout command that:
- [ ] gives the ability to users to do their own logout, if they are logged in, using ssh
- [x] gives bot admins the ability to logout everyone
- [ ] admins can change the logout hour if they decide a member has been erroneously logged in for too long after going away

**Comment by lvps** [comment]
@e-caste This will need extreme modding to the weeelab (it saves the master log in a local file, then overwrites the cloud log) asd

**Comment by e-caste** [comment]
Then the bot should add a flag at the end of the logout line in the log file that weeelab recognizes and causes it to ignore it. Right?

**Comment by lvps** [comment]
@e-caste Nah, let's use the cloud synced log as the master log and be done with it, it's simpler asd
We just need to remove the "copy log files around" part from weeelab asd

**Comment by e-caste** [comment]
Then you can do that part and I'll try and implement this in the telegram bot asd

**Comment by lvps** [comment]
@e-caste Add an issue to the weeelab saying "do that part" asd

**Comment by e-caste** [comment]
This issue is closed.
