### ISSUE TITLE
Improve birthday message

### ISSUE THREAD

**Issue by ZubatZeta** [WEEE-Open/weeelab-telegram-bot#68]
The message sent from the bot to celebrate somebody's birthday can be improved in some ways:
- [ ] Tagging the person with the proper Telegram username, if any
- [ ] ~~Using a number of "cake emoticons" equal to the new age~~

Update: the second idea is under discussion, since some people don't like it.

**Comment by lvps** [comment]
@ZubatZeta If they don't have an username, you can tag them by id (which also notifies them)

**Comment by e-caste** [comment]
@lvps Also, a Telegram first_name is mandatory, so I can use that between quotes to better identify the person (the ID is required in this case, but everyone already inside the team has one, so it shouldn’t be an issue)
